-- liquibase formatted sql

-- changeset Caveri:1

create table "shelter_info"
(
    id                               bigint generated by default as identity PRIMARY KEY,
    about_shelter                    text not null,
    address_and_schedule             text not null,
    safety_contact_for_car_pass      text not null,
    safety_on_territory              text not null,
    first_meet                       text not null,
    documents                        text not null,
    transportation_advice            text not null,
    house_rules_for_small_animal     text not null,
    house_rules_for_adult_animal     text not null,
    rules_for_animal_with_disability text not null,
    cynologist_advice                text,
    cynologists                      text,
    refuse_reasons                   text
);

-- changeset Caveri:2

create table "shelters_user"
(
    id         bigint not null generated by default as identity primary key,
    name        varchar(255) not null,
    surname       varchar(255),
    phone_number       varchar(255),
    data_adopt       DATE,
    chat_id bigint not null,
    animal_id bigint,
    user_type int

);

-- changeset Caveri:3

create table "animal"
(
    id         bigint not null generated by default as identity primary key,
    type_animal        varchar(255) not null,
    breed       varchar(255),
    in_shelter boolean
    );

-- changeset Caveri:4

alter TABLE shelters_user ADD FOREIGN KEY (animal_id) REFERENCES animal(id);

-- changeset Caveri:5

create table "report"
(
    id         bigint not null generated by default as identity primary key,
    photo       text,
    local_date       DATE,
    report_text_under_photo text,
    shelter_users_id bigint
    );

-- changeset Caveri:6

insert into animal (type_animal, breed, in_shelter) values ('CAT', 'Рыжий', true ), ('CAT', 'Сфинкс', true ), ('CAT', 'Дворняжка', true ), ('CAT', 'Британец', true );

-- changeset Caveri:7

insert into animal (type_animal, breed, in_shelter) values ('DOG', 'Овчарка', true), ('DOG', 'Спаниель', true), ('DOG', 'Хаски', true), ('DOG', 'Шпиц', true);


-- changeset Caveri:8

insert into public.shelter_info (about_shelter, address_and_schedule, safety_contact_for_car_pass, safety_on_territory,
                                 first_meet, documents, transportation_advice, house_rules_for_small_animal,
                                 house_rules_for_adult_animal, rules_for_animal_with_disability, cynologist_advice,
                                 cynologists, refuse_reasons)
values ('Наша миссия - защитить животных, подарить им заботу и найти новый дом.','ООО "Кошкин Дом", ул Кошечкина, д.1. Тел. 89000000000',
        'Для оформления пропуска обратитесь, пожалуйста, в службу охраны по телефону 89001111111',
        'Пожалуйста, ознакомьтесь с Правилами нахождения на территории приюта по ссылке: https://zovpredkov.net/pravila-priyuta/',
        'Подготовьтесь к первой встрече с потенциальным питомцем. Много полезных советов можно найти здесь: https://www.hillspet.ru/pet-care/new-pet-parent/what-to-expect-when-visiting-an-animal-shelter',
        'Возьмите с собой паспорт. Это необходимо для проверки данных и подписания договора. Договор - это внутренний документ, который остается в приюте. ',
        'Пожалуйста, ознакомьтесь с рекомендациями по перевозке домашних животных по ссылке: https://dzen.ru/a/YmeaNDHFIXAie2zJ',
        'Подготовьтесь к появлению котенка в своем доме: https://dzen.ru/a/YrlvC9hTxktReHod',
        'Подготовьте свой дом к появлению кошки: https://bfba.ru/chelovek-i-koshka/podgotovka-doma-k-poyavleniyu-koshki.html',
        'Если ваше животное - особенное, то будьте готовы к тому, что и уход ему нужен будет особый. https://petscage.ru/blog/kak-oblegchit-zhizn-zhivotnomu-invalidu/',
        null, null, null);

-- changeset Caveri:9

insert into public.shelter_info (about_shelter, address_and_schedule, safety_contact_for_car_pass, safety_on_territory,
                                 first_meet, documents, transportation_advice, house_rules_for_small_animal,
                                 house_rules_for_adult_animal, rules_for_animal_with_disability, cynologist_advice,
                                 cynologists, refuse_reasons)
values ('Наша миссия - защитить животных, подарить им заботу и найти новый дом.',
        'ООО "Собака - друг человека", ул. Собакевича, 25. Тел. 8921654321',
        'Для оформления пропуска обратитесь, пожалуйста, в службу охраны по телефону 89001111111',
        'Пожалуйста, ознакомьтесь с Правилами нахождения на территории приюта по ссылке: https://zovpredkov.net/pravila-priyuta/',
        'Подготовьтесь к первой встрече с потенциальным питомцем. Много полезных советов можно найти здесь: https://www.hillspet.ru/pet-care/new-pet-parent/what-to-expect-when-visiting-an-animal-shelter',
        'Возьмите с собой паспорт. Это необходимо для проверки данных и подписания договора. Договор - это внутренний документ, который остается в приюте.',
        'Пожалуйста, ознакомьтесь с рекомендациями по перевозке домашних животных по ссылке: https://dzen.ru/a/YmeaNDHFIXAie2zJ',
        'Подготовьтесь к появлению щенка в своем доме: https://dzen.ru/a/YrlvC9hTxktReHod',
        'Подготовьте свой дом к появлению собаки: https://zooclub.ru/dogs/povedeniye-psikhologiya/berem-vzrosluyu-sobaku.shtml',
        'Если ваше животное - особенное, то будьте готовы к тому, что и уход ему нужен будет особый. https://petscage.ru/blog/kak-oblegchit-zhizn-zhivotnomu-invalidu/',
        'Советы кинологов начинающим собаководам: https://ria.ru/20230115/kinolog-1844921406.html',
        'Актуальный список опытных кинологов может выдать волонтер.',
        'Вам могут отказать в усыновлении собаки по следующим причинам: https://kot-pes.com/5-prichin-pochemu-v-priyute-vam-mogut-ne-dat-zhivotnoe/#i-2');